/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsul.dabd.gui.pacientes;

import br.edu.ifsul.dabd.gui.funcionario.JPanelFuncionario;
import br.edu.ifsul.dabd.model.Paciente;
import javax.swing.JOptionPane;


/**
 *
 * @author 20172210032
 */
public class JPanelEdicaoPaciente extends javax.swing.JPanel {
    
    private JPanelPaciente pnlPaciente;
    /**
     * Creates new form JPanelEdicaoPaciente
     */
    public JPanelEdicaoPaciente() {
        initComponents();
    }

   public JPanelEdicaoPaciente(JPanelPaciente p) {
        this.pnlPaciente = p;
        initComponents();
    }
   public void  setDadosFormulario(Paciente p){
        if(p == null){
            txfCodigo.setText("");
            txfNome.setText("");
            txfCpf.setText("");
            txfTelefone.setText("");
            txfCep.setText("");
        }else{
            txfCodigo.setText(p.getCodigo().toString());
            txfNome.setText(p.getNome());
            txfCpf.setText(p.getCpf());
            txfTelefone.setText(p.getTelefone());
            txfCep.setText(p.getCep());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlInferior = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txfCodigo = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txfNome = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        txfCpf = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txfTelefone = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        txfCep = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        pnlInferior.add(btnSalvar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlInferior.add(btnCancelar);

        add(pnlInferior, java.awt.BorderLayout.PAGE_END);

        java.awt.GridBagLayout pnlCentroLayout = new java.awt.GridBagLayout();
        pnlCentroLayout.columnWidths = new int[] {0, 5, 0};
        pnlCentroLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        pnlCentro.setLayout(pnlCentroLayout);

        lblCodigo.setText("Codigo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlCentro.add(lblCodigo, gridBagConstraints);

        txfCodigo.setEditable(false);
        txfCodigo.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pnlCentro.add(txfCodigo, gridBagConstraints);

        lblNome.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnlCentro.add(lblNome, gridBagConstraints);

        txfNome.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        pnlCentro.add(txfNome, gridBagConstraints);

        lblCpf.setText("CPF");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        pnlCentro.add(lblCpf, gridBagConstraints);

        txfCpf.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        pnlCentro.add(txfCpf, gridBagConstraints);

        lblTelefone.setText("Telefone");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        pnlCentro.add(lblTelefone, gridBagConstraints);

        txfTelefone.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        pnlCentro.add(txfTelefone, gridBagConstraints);

        lblCep.setText("CEP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        pnlCentro.add(lblCep, gridBagConstraints);

        txfCep.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        pnlCentro.add(txfCep, gridBagConstraints);

        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String nome = txfNome.getText().trim();
        String cpf = txfCpf.getText().trim();
        String tel = txfTelefone.getText().trim();
        String cep = txfCep.getText().trim();

        if(nome.length() > 0 && cpf.length() > 0 && tel.length() > 0 && cep.length() > 0){
            Paciente p = new Paciente();
            p.setNome(nome);
            p.setCpf(cpf);
            p.setTelefone(tel);
            p.setCep(cep);
            //testar a acao: inserir novo ou editar existente
            String ret;
            String acao;
            if(txfCodigo.getText().trim().length() > 0){
                p.setCodigo(Integer.parseInt(txfCodigo.getText().trim()));//adiciona o codigo do funcionario
                ret = pnlPaciente.getControle().getConexao().updatePaciente(p);
                acao = "Editou";
            }else{
                ret = pnlPaciente.getControle().getConexao().insertPaciente(p);
                acao = "Inseriu";
            }
            if(ret == null){
                JOptionPane.showMessageDialog(this, acao+" Paciente!", acao, JOptionPane.INFORMATION_MESSAGE);
                //atualiza a listagem
                pnlPaciente.getListagem().populaTabela();
                pnlPaciente.showTela("tela_listagem");
                
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao inserir Paciente :"+ret, "Inserção", JOptionPane.ERROR_MESSAGE);
            }
           
            
        }else{
            JOptionPane.showMessageDialog(this, "Preencha o formulário!!", "Paciente", JOptionPane.INFORMATION_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        pnlPaciente.showTela("tela_listagem");        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlInferior;
    private javax.swing.JTextField txfCep;
    private javax.swing.JTextField txfCodigo;
    private javax.swing.JTextField txfCpf;
    private javax.swing.JTextField txfNome;
    private javax.swing.JTextField txfTelefone;
    // End of variables declaration//GEN-END:variables
}
